//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrenteDeCaixa.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FrenteDeCaixa.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes (F6).
        /// </summary>
        public static string ButtonClientes {
            get {
                return ResourceManager.GetString("ButtonClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizar Venda (F3).
        /// </summary>
        public static string ButtonFinalizarVenda {
            get {
                return ResourceManager.GetString("ButtonFinalizarVenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formas de Pagamento (F8).
        /// </summary>
        public static string ButtonFormasDePagamento {
            get {
                return ResourceManager.GetString("ButtonFormasDePagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produtos (F7).
        /// </summary>
        public static string ButtonProdutos {
            get {
                return ResourceManager.GetString("ButtonProdutos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios (F5).
        /// </summary>
        public static string ButtonUsuarios {
            get {
                return ResourceManager.GetString("ButtonUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendas (F9).
        /// </summary>
        public static string ButtonVendas {
            get {
                return ResourceManager.GetString("ButtonVendas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string ClienteDB {
            get {
                return ResourceManager.GetString("ClienteDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FormaDePagamento.
        /// </summary>
        public static string FormaDePagamentoDB {
            get {
                return ResourceManager.GetString("FormaDePagamentoDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frente de Caixa.
        /// </summary>
        public static string FrenteDeCaixa {
            get {
                return ResourceManager.GetString("FrenteDeCaixa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemVenda.
        /// </summary>
        public static string ItemVendaDB {
            get {
                return ResourceManager.GetString("ItemVendaDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operador: .
        /// </summary>
        public static string Operador {
            get {
                return ResourceManager.GetString("Operador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PerfilDeUsuario.
        /// </summary>
        public static string PerfilDeUsuarioDB {
            get {
                return ResourceManager.GetString("PerfilDeUsuarioDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto.
        /// </summary>
        public static string ProdutoDB {
            get {
                return ResourceManager.GetString("ProdutoDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente (F4).
        /// </summary>
        public static string TextBoxCliente {
            get {
                return ResourceManager.GetString("TextBoxCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto (F2).
        /// </summary>
        public static string TextBoxProduto {
            get {
                return ResourceManager.GetString("TextBoxProduto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: .
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string UsuarioDB {
            get {
                return ResourceManager.GetString("UsuarioDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venda.
        /// </summary>
        public static string VendaDB {
            get {
                return ResourceManager.GetString("VendaDB", resourceCulture);
            }
        }
    }
}
